export const SELECT_ACCOUNT_REQUEST = 'SELECT_ACCOUNT_REQUEST';
export const SELECT_ACCOUNT_SUCCESS = 'SELECT_ACCOUNT_SUCCESS';
export const SELECT_ACCOUNT_FAILURE = 'SELECT_ACCOUNT_FAILURE';
// 商品查询
export const SELECT_PRODUCTS_REQUEST = 'SELECT_PRODUCTS_REQUEST';
export const SELECT_PRODUCTS_SUCCESS = 'SELECT_PRODUCTS_SUCCESS';
export const SELECT_PRODUCTS_FAILURE = 'SELECT_PRODUCTS_FAILURE';