const actionTypes = {
    // 登录查询
    SELECT_ACCOUNT_REQUEST: 'SELECT_ACCOUNT_REQUEST',
    SELECT_ACCOUNT_SUCCESS: 'SELECT_ACCOUNT_SUCCESS',
    SELECT_ACCOUNT_FAILURE: 'SELECT_ACCOUNT_FAILURE',
    // 商品查询
    SELECT_PRODUCTS_REQUEST: 'SELECT_PRODUCTS_REQUEST',
    SELECT_PRODUCTS_SUCCESS: 'SELECT_PRODUCTS_SUCCESS',
    SELECT_PRODUCTS_FAILURE: 'SELECT_PRODUCTS_FAILURE'
};

export default actionTypes;